---
title: "20200107-millRiver_covidStudy_jsg2145"
author: "Jared Garfinkel"
date: "1/7/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(readxl)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 6, 
  fig.height = 8,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Part 1

## Read in data

```{r}
cases = readxl::read_excel("./data/NassauCountyCOVID.xlsx") %>% 
  janitor::clean_names() %>% 
  select(namelsad, pos_12102020)

cases
```

```{r}
df = readxl::read_excel("./data/DianaData_11_25_20.xlsx") %>% 
  janitor::clean_names()

# observe dataframe

# skimr::skim(df)

# missing data in "median rooms", "mhv", and "mhi"

# df %>%
# filter(is.na(mhi))
```

## merge datasets

```{r}
data = left_join(df, cases, by = c("geographic_area_name" = "namelsad")) %>% 
  select(geographic_area_name, pos_12102020, everything())
# data
```

## exploratory data analysis

```{r, include = FALSE, eval = FALSE}
# ncol(data)
data[2]
pull(data, 2)
output = NULL
for(i in 2:ncol(data)) {
  output[[i]] = data %>%  
    ggplot(aes(x = pull(data, i))) +
    geom_boxplot()
}
output
```


```{r, fig.height = 12, fig.width = 14}
box_df = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  slice_head(mean, n = 1)
# box_df
```

```{r}
box_df %>%
  # group_by(name) %>% 
  ggplot(aes(x = name, y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r works}
box_df2 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(2:3))
 # box_df2
```

```{r}
box_df2 %>%
  # mutate(mean = factor(mean)) %>%
  # arrange(mean) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df3 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(4:7))
# box_df3

box_df3 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df4 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(8:12))
# box_df3

box_df4 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df5 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(13:18))
# box_df3

box_df5 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df6 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(19:25))
# box_df3

box_df6 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df7 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>% 
  filter(row_number() %in% c(26:33))
# box_df3

box_df7 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
box_df8 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  ungroup() %>%
  group_by(geographic_area_name) %>% 
  arrange(desc(mean)) %>%
  filter(row_number() %in% c(34:45))
# box_df3

box_df8 %>%
  # mutate(mean = as_factor(mean),
  #        name = as_factor(name)) %>% 
  # group_by(name) %>% 
  ggplot(aes(x = fct_reorder(name, value), y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1))
```

# Notes

```{r, include = FALSE, eval = FALSE}
data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>% 
  # ungroup() %>%
  group_by(mean) %>% 
  mutate(rank = rank(mean))
  # filter(mean == nth(rank(mean), 1))
  
box_df2 = data %>% 
  pivot_longer(cols = 2:ncol(.)) %>% 
  # mutate(name = factor(name)) %>% 
  group_by(name) %>% 
  mutate(mean = mean(value)) %>% 
         # mean = factor(mean)) %>%
  filter(!is.na(mean)) %>%
  # ungroup() %>%
  arrange(desc(mean)) %>% 
  select(name, mean) %>% 
  distinct()
box_df2
```

```{r, include = FALSE, eval = FALSE}
# box_df = data %>% 
#   pivot_longer(cols = 2:ncol(.)) %>% 
#   group_by(name, mean(value))

# str(box_df)
# ?slice_max

# choose the top 5 variables (name) by mean (mean(value))



box_df = box_df %>% 
  slice_max(mean, n = 134*5)

str(box_df)
```


```{r, include= FALSE, eval = FALSE}
box_df %>%
  group_by(name) %>% 
  ggplot(aes(x = name, y = value, group = name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  

```

# Linear Regression

## conduct linear regression

```{r}
fit = glm(pos_12102020 ~ ., data = data[,-1], family = poisson(link = "log"))
summary(fit)
```

## test for goodness of fit

```{r}
sum(residuals(fit,type='pearson')^2) # pearson chisq
dev=sum(residuals(fit,type='deviance')^2)
dev # deviance
# compare with chisq(112)
pval=1-pchisq(dev,112)
pval # fit is not good
```

## plot goodness of fit diagnostics

```{r}
plot(fit)
```
